const FIRST_VALUE_DEFAULT = 0;
const FIRST_VALUE_PERCENT_DEFAULT = 0;
const MIN_VALUE_DEFAULT = 0;
const MAX_VALUE_DEFAULT = 100;
const STEP_VALUE_DEFAULT = 1;
const PERCENT_MIN = 0;
const PERCENT_MAX = 100;

export {
  FIRST_VALUE_DEFAULT,
  FIRST_VALUE_PERCENT_DEFAULT,
  MIN_VALUE_DEFAULT,
  MAX_VALUE_DEFAULT,
  PERCENT_MIN,
  PERCENT_MAX,
  STEP_VALUE_DEFAULT,
 };
